---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/books":
    get:
      summary: list books
      tags:
      - Books
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
